### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ph4ge**
Added darcs.net and pijul.org VCS.

### CODE REVIEW

**Comment by gdamdam** [comment]
the darcs.net website is unreachable

**Comment by ph4ge** [comment]
Yes, indeed. It was up a few days ago.

**Comment by gdamdam** [comment]
please submit pull requestswith only working urls.

**Comment by ph4ge** [comment]
I removed darcs from the list.

**Comment by gdamdam** [comment]
thank you

**Comment by ph4ge** [comment]
totally makes sense.

**Pull request merged**
