### PR TITLE
Add remoteStorage

### PR DESCRIPTION
**Pull request by rosano**

### CODE REVIEW

**Comment by gdamdam** [comment]
it does not seems a decentralized web project to me.

**Comment by rosano** [comment]
It's an open protocol for users to bring their own data storage when using apps. It's decentralized like email in that anyone can self-host or they can find a provider. Many apps are also serverless and hold no data, everything running in the browser. See 0data.app

**Comment by rosano** [comment]
Actually you could also just think of it as SOLID (which is on the list) but using common JSON instead of RDF.

**Comment by gdamdam** [comment]
thnk you

**Pull request merged**
