### PR TITLE
Add Fission webnative

### PR DESCRIPTION
**Pull request by rosano**

### CODE REVIEW

**Comment by gdamdam** [comment]
Fissions seems an "app hosting marketplace for developers and users that supports web native apps."
And not a particular decentralized web technology...

**Comment by rosano** [comment]
They're doing many things at the same time but the link is more for 'Webnative', which is a JavaScript library that decouples user data from apps and hosts it on IPFS. It's described more in the second section under the video.

Might have been better to link to the SDK directly but I think it's better explained from front page https://guide.fission.codes/developers/webnative

**Comment by gdamdam** [comment]
can you focus the entry on 'Webnative'? which is a JavaScript library that decouples user data from apps and hosts it on IPFS.

**Comment by rosano** [comment]
Done.

**Comment by gdamdam** [comment]
nice! tnx

**Pull request merged**
